# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 146b7aec0b2298e8d4aeeaef5bf420c41ebfba5547a4a00e5b9c5532d6848fa4913eac698f98a3b07842c327d8c7795b58fc762db94219c98b8c40209665ec47

test:
  secret_key_base: a4a622d7ef8b6bc3af639d3d79046522afd6651a042758cc9c81c376a53d1559af3059c5d2e7350c24b2ccd485b4b5a7b2a07863a001aeaf6d8614236fd0089a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
